LIBS+= /usr/local/lib/libopencv_videostab.so.2.4\ 
  /usr/lib/x86_64-linux-gnu/libopencv_videostab.so.2.4\ 
  /usr/local/lib/libopencv_videostab.so\ 
  /usr/lib/x86_64-linux-gnu/libopencv_videostab.so\ 
  /usr/local/lib/libopencv_video.so.2.4\ 
  /usr/lib/x86_64-linux-gnu/libopencv_video.so.2.4\ 
  /usr/local/lib/libopencv_video.so\ 
  /usr/lib/x86_64-linux-gnu/libopencv_video.so\ 
  /usr/lib/x86_64-linux-gnu/libopencv_ts.so.2.4\ 
  /usr/lib/x86_64-linux-gnu/libopencv_ts.so\ 
  /usr/local/lib/libopencv_superres.so.2.4\ 
  /usr/lib/x86_64-linux-gnu/libopencv_superres.so.2.4\ 
  /usr/local/lib/libopencv_superres.so\ 
  /usr/lib/x86_64-linux-gnu/libopencv_superres.so\ 
  /usr/local/lib/libopencv_stitching.so.2.4\ 
  /usr/lib/x86_64-linux-gnu/libopencv_stitching.so.2.4\ 
  /usr/local/lib/libopencv_stitching.so\ 
  /usr/lib/x86_64-linux-gnu/libopencv_stitching.so\ 
  /usr/local/lib/libopencv_photo.so.2.4\ 
  /usr/lib/x86_64-linux-gnu/libopencv_photo.so.2.4\ 
  /usr/local/lib/libopencv_photo.so\ 
  /usr/lib/x86_64-linux-gnu/libopencv_photo.so\ 
  /usr/local/lib/libopencv_ocl.so.2.4\ 
  /usr/lib/x86_64-linux-gnu/libopencv_ocl.so.2.4\ 
  /usr/local/lib/libopencv_ocl.so\ 
  /usr/lib/x86_64-linux-gnu/libopencv_ocl.so\ 
  /usr/local/lib/libopencv_objdetect.so.2.4\ 
  /usr/lib/x86_64-linux-gnu/libopencv_objdetect.so.2.4\ 
  /usr/local/lib/libopencv_objdetect.so\ 
  /usr/lib/x86_64-linux-gnu/libopencv_objdetect.so\ 
  /usr/local/lib/libopencv_nonfree.so.2.4\ 
  /usr/local/lib/libopencv_nonfree.so\ 
  /usr/local/lib/libopencv_ml.so.2.4\ 
  /usr/lib/x86_64-linux-gnu/libopencv_ml.so.2.4\ 
  /usr/local/lib/libopencv_ml.so\ 
  /usr/lib/x86_64-linux-gnu/libopencv_ml.so\ 
  /usr/local/lib/libopencv_legacy.so.2.4\ 
  /usr/lib/x86_64-linux-gnu/libopencv_legacy.so.2.4\ 
  /usr/local/lib/libopencv_legacy.so\ 
  /usr/lib/x86_64-linux-gnu/libopencv_legacy.so\ 
  /usr/local/lib/libopencv_imgproc.so.2.4\ 
  /usr/lib/x86_64-linux-gnu/libopencv_imgproc.so.2.4\ 
  /usr/local/lib/libopencv_imgproc.so\ 
  /usr/lib/x86_64-linux-gnu/libopencv_imgproc.so\ 
  /usr/local/lib/libopencv_highgui.so.2.4\ 
  /usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4\ 
  /usr/local/lib/libopencv_highgui.so\ 
  /usr/lib/x86_64-linux-gnu/libopencv_highgui.so\ 
  /usr/local/lib/libopencv_gpu.so.2.4\ 
  /usr/lib/x86_64-linux-gnu/libopencv_gpu.so.2.4\ 
  /usr/local/lib/libopencv_gpu.so\ 
  /usr/lib/x86_64-linux-gnu/libopencv_gpu.so\ 
  /usr/local/lib/libopencv_flann.so.2.4\ 
  /usr/lib/x86_64-linux-gnu/libopencv_flann.so.2.4\ 
  /usr/local/lib/libopencv_flann.so\ 
  /usr/lib/x86_64-linux-gnu/libopencv_flann.so\ 
  /usr/local/lib/libopencv_features2d.so.2.4\ 
  /usr/lib/x86_64-linux-gnu/libopencv_features2d.so.2.4\ 
  /usr/local/lib/libopencv_features2d.so\ 
  /usr/lib/x86_64-linux-gnu/libopencv_features2d.so\ 
  /usr/local/lib/libopencv_core.so.2.4\ 
  /usr/lib/x86_64-linux-gnu/libopencv_core.so.2.4\ 
  /usr/local/lib/libopencv_core.so\ 
  /usr/lib/x86_64-linux-gnu/libopencv_core.so\ 
  /usr/local/lib/libopencv_contrib.so.2.4\ 
  /usr/lib/x86_64-linux-gnu/libopencv_contrib.so.2.4\ 
  /usr/local/lib/libopencv_contrib.so\ 
  /usr/lib/x86_64-linux-gnu/libopencv_contrib.so\ 
  /usr/local/lib/libopencv_calib3d.so.2.4\ 
  /usr/lib/x86_64-linux-gnu/libopencv_calib3d.so.2.4\ 
  /usr/local/lib/libopencv_calib3d.so\ 
  /usr/lib/x86_64-linux-gnu/libopencv_calib3d.so
